// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6rV8pKlRMJZ3xNHbuVJg6cxljLH0zG44',
    appId: '1:730037841272:web:14e63e9c0142f2941f2c8d',
    messagingSenderId: '730037841272',
    projectId: 'trusparemain',
    authDomain: 'trusparemain.firebaseapp.com',
    storageBucket: 'trusparemain.appspot.com',
    measurementId: 'G-TDYZ7SY47D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSv4N8IIzFu2aqNeiXOm5TVkyOtdYNSU4',
    appId: '1:730037841272:android:b28461bbfac6c3871f2c8d',
    messagingSenderId: '730037841272',
    projectId: 'trusparemain',
    storageBucket: 'trusparemain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4FEjTVphbPIoiUtZyTVKU6LJ4Cx-mzGw',
    appId: '1:730037841272:ios:4ecdfffb254798701f2c8d',
    messagingSenderId: '730037841272',
    projectId: 'trusparemain',
    storageBucket: 'trusparemain.appspot.com',
    iosClientId: '730037841272-5rraumfslkqup40ioqc289mces5qhp19.apps.googleusercontent.com',
    iosBundleId: 'com.trusparemain.trusparemain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4FEjTVphbPIoiUtZyTVKU6LJ4Cx-mzGw',
    appId: '1:730037841272:ios:46c537f0f4fa1d561f2c8d',
    messagingSenderId: '730037841272',
    projectId: 'trusparemain',
    storageBucket: 'trusparemain.appspot.com',
    iosClientId: '730037841272-1eau2t57ddgeha0djde78gf9tc4g35r2.apps.googleusercontent.com',
    iosBundleId: 'com.trusparemain.trusparemain.RunnerTests',
  );
}
